### ISSUE TITLE
Please Update to V9

### ISSUE THREAD

**Issue by PhluXx1** [shawndibble/foundryvtt-show-notes#3]
Would really appreciate a V9 update if you could please update. This is a really great module that removes a lot of potential user error on the players end.

**Comment by CaosFR** [comment]
Same , please update your great mob.

**Comment by shawndibble** [comment]
Can you provide an error from the console.log you maybe getting? I just installed v9 of foundry and the module works fine. I can do a compatibility update. Just want to make sure there are no bugs.

**Comment by CaosFR** [comment]
It's looking to work, I have no error or strange comportement. I'm working on a new server and I dont have any player to see if it's work totaly correctly.

Just disable the warning will be enough.

**Comment by shawndibble** [comment]
An updated version has been published that should work for v9.

**Comment by CaosFR** [comment]
Thanks for your work.
