### ISSUE TITLE
Compatibility warning: not verified for v10

### ISSUE THREAD

**Issue by yjeroen** [shawndibble/foundryvtt-show-notes#4]
![image](https://user-images.githubusercontent.com/1303988/200176981-2390008b-73d2-4114-91b7-8be9960d0918.png)

Would be great if the module.json could be updated if the module is compatible with Foundry V10.

**Comment by shawndibble** [comment]
Updated for v10
https://github.com/shawndibble/foundryvtt-show-notes/releases/tag/10
