### ISSUE TITLE
v11 warnings

### ISSUE THREAD

**Issue by rafacrudi** [shawndibble/foundryvtt-show-notes#6]
The module "foundryvtt-show-notes" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object
The module "foundryvtt-show-notes" is using "name" which is deprecated in favor of "id"

**Comment by shawndibble** [comment]
https://github.com/shawndibble/foundryvtt-show-notes/releases/tag/11.1 released and pushed to foundry.
