### ISSUE TITLE
Error in module.json preventing update

### ISSUE THREAD

**Issue by esheyw** [shawndibble/foundryvtt-show-notes#7]
![](https://i.imgur.com/YFFjx8v.png)

missing comma after the compatibility object. grr json.

**Comment by rafacrudi** [comment]
![image](https://github.com/shawndibble/foundryvtt-show-notes/assets/74941182/40e7ff85-06c3-47a3-8121-4e37f4b85046)

**Comment by rafacrudi** [comment]
"compatibility": {
		"minimum": "0.6.0",
		"verified": "11"
	}
	
	Line 10, a comma after "}"
	;)

**Comment by shawndibble** [comment]
Thanks for the update. https://github.com/shawndibble/foundryvtt-show-notes/releases/tag/11.2 has been pushed out.
